### ISSUE TITLE
gimli/libbacktrace don't handle dynamically loaded libraries

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/backtrace-rs#238]
Currently iteration over all dynamic objects happens once in libbacktrace/gimli (gimli for sure, libbacktrace is a best approximation). This means that if a backtrace is generated and then afterwards a dynamic object is loaded (e.g. via `dlopen`) the backtraces through that new dynamic object may be missing symbol information. We'll likely need to add a fallback in gimli where if a symbol doesn't hit the cache of libraries we know about we check again to see if any new libraries have been opened.

**Comment by t-mw** [comment]
Could this explain backtraces in dynamically loaded libraries becoming `<unknown>` between Rust 1.36 and 1.37? I also saw that https://github.com/rust-lang/rust/pull/57967 was causing similar issues in >= 1.37 (https://github.com/rust-lang/rust/issues/61416), but those appear to have been fixed.

**Comment by alexcrichton** [comment]
I don't believe this is related to gimli because gimli isn't used in libstd. That being said that still sounds like a regression that's likely related to this crate! (just separate)

**Comment by t-mw** [comment]
Thanks, I've filed a separate issue at https://github.com/rust-lang/rust/issues/67599.

**Comment by itamarst** [comment]
Assuming this is still a problem, would calling `backtrace::clear_symbol_cache()` after every `dlopen()` be an effective workaround?

**Comment by jmrgibson** [comment]
At least on 0.36:
1) this is still a problem
2) calling `clear_symbol_cache()` doesn't clear `cache.libraries`, only `cache.mappings`. So if you load a new library, you won't get any new symbols.

I'll put up a PR for this shortly.

**Comment by jmrgibson** [comment]
Given that `cache.mappings` has indexes into `cache.libraries`, I think I'll make a new function that clears both `cache.libraries` AND `cache.mappings`.

**Comment by bjorn3** [comment]
> We'll likely need to add a fallback in gimli where if a symbol doesn't hit the cache of libraries we know about we check again to see if any new libraries have been opened.

I think this is a better solution that requiring users to call a function to clear the cache.
